apiVersion: v1
kind: Service
metadata:
  name: {{ include "projet-hydro.fullname" . }}
  labels:
    {{- include "projet-hydro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "projet-hydro.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
